

using System.Runtime.Intrinsics.X86;

//namespace Assign2
//{

//    Properties
//----------
//string Name -> no blank names should be allowed
//int EmpNo ->  must be readonly and autogenerated
//decimal Basic -> must be between some range
//short DeptNo -> must be > 0

//Methods
//-------
//decimal GetNetSalary() -> returns calculated net salary(Use any formula to get net salary based on Basic salary)


//Create constructors to accept initial values for Employee obj
//Employee o1 = new Employee("Amol", 123465, 10);
//    Employee o2 = new Employee("Amol", 123465);
//    Employee o3 = new Employee("Amol");
//    Employee o4 = new Employee();

//    EmpNo must be autogenerated...i.e.
//    first object should automatically get EmpNo 1
//second object should automatically get EmpNo 2
//third object should automatically get EmpNo 3
//...and so on...

//    Test Cases
//    Employee o1 = new Employee()
//    Employee o2 = new Employee()
//    Employee o3 = new Employee()
//    cw(o1.EmpNo)
//    cw(o2.EmpNo)
//    cw(o3.EmpNo)

//    cw(o3.EmpNo)
//    cw(o2.EmpNo)
//    cw(o1.EmpNo)

    internal class Program
    {
        static void Main(string[] args)
        {
        Employee o1 = new Employee("amol", 123465, 10);
        Employee o2 = new Employee("amol", 123465);
        Employee o3 = new Employee("amol");
        Employee o4 = new Employee();

        display(o1);
        display(o2);
        display(o3);
        display(o4);

        Employee o11 = new Employee();
            Employee o22 = new Employee();
            Employee o33 = new Employee();

            Console.WriteLine(o11.EmpNo);
            Console.WriteLine(o22.EmpNo);
            Console.WriteLine(o33.EmpNo);

            Console.WriteLine(o33.EmpNo);
            Console.WriteLine(o22.EmpNo);
            Console.WriteLine(o11.EmpNo);

        }
        public static void display(Employee e)
        {
            Console.WriteLine(e.Name + " " + e.EmpNo + " " + e.Basic + " " + e.DeptNo);
        }

    }
    public class Employee
{
        public int EmpNo { get; set; }
    public string Name { get; set; }
    public int Salary { get; set; }

    public Employee(int empNo, string name, int salary)
    {
        EmpNo = empNo;
        Name = name;
        Salary = salary;
    }
    }